### ISSUE TITLE
Add use to cash

### ISSUE THREAD

**Issue by TortillaWrappedParrot** [NullPointer1331/GameShopManager#36]
- Use cash to buy items to the user's inventory, 80% of the item price they are purchasing
- Use cash to buy items to add the db, a percent plus the item price your trying to sell for, ex. item price is 100, pay 150 to add the item

**Comment by NullPointer1331** [comment]
I'm not quite sure what you mean by "Use cash to buy items to add the db"

**Comment by TortillaWrappedParrot** [comment]
The add item form where you put a name, price, and description. Could be a fee like adding a new product to a store.

**Comment by NullPointer1331** [comment]
If we're going to be using cash, we will also need a way to gain cash

**Comment by TortillaWrappedParrot** [comment]
If were doing a shop type game we could make it so you can progress a day and based on your inventoryitems give cash accordingly

**Comment by NullPointer1331** [comment]
If you want to make it into a game, we probably don't need the delete item form. I added the issue with the intent of demonstrating how we've implemented CRUD functionality, but if it's meant to be a game instead of a demonstration, then I don't think it would make sense for a user to have access to it. The add item form is a similar case, though I suppose it could be made into a game mechanic.

**Comment by TortillaWrappedParrot** [comment]
We could keep it as a demonstration however we would still need to find something to do with the cash and item price.

**Comment by NullPointer1331** [comment]
We could give Users some starting cash when they're created, and allow them to sell their InventoryItems instead of just removing them. Not sure if it would be best to let them set the price, set a % markup, or just sell them at a markup that we set.
